export const GET_FOODS = 'GET_FOODS'
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS'
export const GET_FOODS_FAILURE = 'GET_FOODS_FAILURE'

export const GET_ALL_FOODS = 'GET_ALL_FOODS'
export const GET_ALL_FOODS_SUCCESS = 'GET_ALL_FOODS_SUCCESS'
export const GET_ALL_FOODS_FAILURE = 'GET_ALL_FOODS_FAILURE'

export const EDIT_FOODS = 'EDIT_FOODS'
export const EDIT_FOODS_SUCCESS = 'EDIT_FOODS_SUCCESS'
export const EDIT_FOODS_FAILURE = 'EDIT_FOODS_FAILURE'


export const CREATE_FOODS = 'CREATE_FOODS'
export const CREATE_FOODS_SUCCESS = 'CREATE_FOODS_SUCCESS'
export const CREATE_FOODS_FAILURE = 'CREATE_FOODS_FAILURE'